---
- name: Add parameters /etc/hosts
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: | 
      192.168.56.10 dc1.test.loc dc1
      192.168.56.15 dc2.test.loc dc2

- name: Update repository
  ansible.builtin.apt:
    update_cache: yes

- name: Install packages
  ansible.builtin.apt:
    pkg:
    - expect
    - acl
    - attr
    - samba
    - samba-dsdb-modules
    - samba-vfs-modules
    - winbind
    - libpam-winbind
    - libnss-winbind
    - libpam-krb5
    - krb5-config
    - krb5-user
    - dnsutils
    - chrony
    - net-tools
    state: latest

- name: Delete file conf
  ansible.builtin.file: 
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/samba/smb.conf
    - /etc/krb5.conf

- name: Add dns sever
  ansible.builtin.copy:
    src: resolv.conf
    dest: /etc/resolv.conf

- name: Join AD Domain Configuration
  ansible.builtin.command: samba-tool domain join {{ realm }} DC -W AD -U Administrator --password={{ adminpass }} 

- name: Copy file krb5.conf
  ansible.builtin.copy:
    src: /var/lib/samba/private/krb5.conf
    dest: /etc/krb5.conf
    remote_src: true

- name: stop service systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped
    enabled: false

- name: Unlink file /etc/resolv.conf
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent

- name: Create file /etc/resolv.conf and add parameters
  ansible.builtin.blockinfile:
    create: true
    path: /etc/resolv.conf
    block: |
      nameserver 192.168.56.15
      search test.loc

- name: Copy file configuration chronyd
  ansible.builtin.copy:
    src: chrony.conf
    dest: /etc/chrony/chrony.conf
    follow: yes

- name: Stoped and masked service
  ansible.builtin.systemd:
    state: stopped
    masked: yes
    enabled: false
    name: "{{ item }}"
  with_items:
    - smbd
    - nmbd
    - winbind

- name: Unmask and start service samba-ad-dc
  ansible.builtin.systemd:
    name: samba-ad-dc
    state: started
    masked: no 
    enabled: yes

- name: Change file ownership, group and permissions /var/lib/samba/ntp_signd
  ansible.builtin.file:
    path: /var/lib/samba/ntp_signd
    owner: root
    group: _chrony
    mode: '0755'

