---
- name: Add parameters /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: 192.168.56.10 dc1.test.loc dc1

- name: Update repository
  ansible.builtin.apt:
    update_cache: yes

- name: Install packages
  ansible.builtin.apt:
    pkg:
    - acl
    - attr
    - samba
    - samba-dsdb-modules
    - samba-vfs-modules
    - winbind
    - libpam-winbind
    - libnss-winbind
    - libpam-krb5
    - krb5-config
    - krb5-user
    - dnsutils
    - chrony
    - net-tools
    - rsync
    - unison
    state: latest

- name: Rename file conf
  ansible.builtin.file: 
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/samba/smb.conf
    - /etc/krb5.conf

- name: Create AD Domain Configuration
  ansible.builtin.command: samba-tool domain provision --server-role=dc --use-rfc2307 --dns-backend=SAMBA_INTERNAL --domain={{ domain }} --adminpass={{ adminpass }} --realm={{ realm }}

- name: Change parameters /etc/samba/smb.conf
  ansible.builtin.replace:
    dest: /etc/samba/smb.conf
    regexp: '127.0.0.53'
    replace: '77.88.8.8  77.88.8.1' 


- name: Copy file krb5.conf
  ansible.builtin.copy:
    src: /var/lib/samba/private/krb5.conf
    dest: /etc/krb5.conf
    remote_src: true

- name: stop service systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped
    enabled: false

- name: Unlink file /etc/resolv.conf
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent

- name: Create file /etc/resolv.conf and add parameters
  ansible.builtin.blockinfile:
    create: true
    path: /etc/resolv.conf
    block: |
      nameserver 192.168.56.10
      search test.loc

- name: Copy file configuration chronyd
  ansible.builtin.copy:
    src: chrony.conf
    dest: /etc/chrony/chrony.conf
    follow: yes

- name: Stoped and masked service
  ansible.builtin.systemd:
    state: stopped
    masked: yes
    enabled: false
    name: "{{ item }}"
  with_items:
    - smbd
    - nmbd
    - winbind

- name: Unmask and start service samba-ad-dc
  ansible.builtin.systemd:
    name: samba-ad-dc
    state: started
    masked: no 
    enabled: yes

- name: Change file ownership, group and permissions /var/lib/samba/ntp_signd
  ansible.builtin.file:
    path: /var/lib/samba/ntp_signd
    owner: root
    group: _chrony
    mode: '0750'

- name: generate SSH key
  ansible.builtin.user:
    name: root
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: view ssh key pub
  shell: cat /root/.ssh/id_rsa.pub
  register: ssh_key_client

- name: input ssh key client in server file
  ansible.builtin.lineinfile:
    path: /root/.ssh/authorized_keys
    line: '{{ssh_key_client.stdout}}' 
  delegate_to: dc2

- name: Create a directory /.ssh/ctl
  ansible.builtin.file:
    path: /root/.ssh/ctl
    state: directory
    mode: '0755'

- name: Copy config file
  ansible.builtin.copy:
    src: config
    dest: /root/.ssh/ctl/config
    follow: yes

- name: Create file sysvol-sync.log
  ansible.builtin.file:
    path: /var/log/unison-sync.log
    state: touch
    mode: '640'

- name: Create a directory /root/.unison
  ansible.builtin.file:
    path: /root/.unison
    state: directory
    mode: '0755'


